blueprint:
  name: Shelly Wave I4 (Z-Wave) 4 Button Actions
  description: For the Shelly Wave I4 (QNSN-0A24X) connected via Z-Wave JS.
  domain: automation
  input:
    button:
      name: Device
      description: Choose your Shelly Wave I4 Z-Wave device
      selector:
        device:
          manufacturer: Shelly Europe Ltd.
          model: QNSN-0A24X
          multiple: false

    pressb1:
      name: Button 1 - Single Press
      default: []
      selector:
        action: {}
    releaseb1:
      name: Button 1 - Released
      default: []
      selector:
        action: {}
    doubleb1:
      name: Button 1 - Double Press
      default: []
      selector:
        action: {}
    longb1:
      name: Button 1 - Held Down
      default: []
      selector:
        action: {}

    pressb2:
      name: Button 2 - Single Press
      default: []
      selector:
        action: {}
    releaseb2:
      name: Button 2 - Released
      default: []
      selector:
        action: {}
    doubleb2:
      name: Button 2 - Double Press
      default: []
      selector:
        action: {}
    longb2:
      name: Button 2 - Held Down
      default: []
      selector:
        action: {}

    pressb3:
      name: Button 3 - Single Press
      default: []
      selector:
        action: {}
    releaseb3:
      name: Button 3 - Released
      default: []
      selector:
        action: {}
    doubleb3:
      name: Button 3 - Double Press
      default: []
      selector:
        action: {}
    longb3:
      name: Button 3 - Held Down
      default: []
      selector:
        action: {}

    pressb4:
      name: Button 4 - Single Press
      default: []
      selector:
        action: {}
    releaseb4:
      name: Button 4 - Released
      default: []
      selector:
        action: {}
    doubleb4:
      name: Button 4 - Double Press
      default: []
      selector:
        action: {}
    longb4:
      name: Button 4 - Held Down
      default: []
      selector:
        action: {}

mode: restart
max_exceeded: silent

trigger:
  - platform: device
    domain: zwave_js
    device_id: !input button
    type: zwave_js.value_notification.Central_Scene
    property: scene
    property_key: "001"
    command_class: 91
    endpoint: 0
    value: "0"
    id: btn1_press
  - platform: device
    domain: zwave_js
    device_id: !input button
    type: zwave_js.value_notification.Central_Scene
    property: scene
    property_key: "001"
    command_class: 91
    endpoint: 0
    value: "1"
    id: btn1_release
  - platform: device
    domain: zwave_js
    device_id: !input button
    type: zwave_js.value_notification.Central_Scene
    property: scene
    property_key: "001"
    command_class: 91
    endpoint: 0
    value: "2"
    id: btn1_long
  - platform: device
    domain: zwave_js
    device_id: !input button
    type: zwave_js.value_notification.Central_Scene
    property: scene
    property_key: "001"
    command_class: 91
    endpoint: 0
    value: "3"
    id: btn1_double

  - platform: device
    domain: zwave_js
    device_id: !input button
    type: zwave_js.value_notification.Central_Scene
    property: scene
    property_key: "002"
    command_class: 91
    endpoint: 0
    value: "0"
    id: btn2_press
  - platform: device
    domain: zwave_js
    device_id: !input button
    type: zwave_js.value_notification.Central_Scene
    property: scene
    property_key: "002"
    command_class: 91
    endpoint: 0
    value: "1"
    id: btn2_release
  - platform: device
    domain: zwave_js
    device_id: !input button
    type: zwave_js.value_notification.Central_Scene
    property: scene
    property_key: "002"
    command_class: 91
    endpoint: 0
    value: "2"
    id: btn2_long
  - platform: device
    domain: zwave_js
    device_id: !input button
    type: zwave_js.value_notification.Central_Scene
    property: scene
    property_key: "002"
    command_class: 91
    endpoint: 0
    value: "3"
    id: btn2_double

  - platform: device
    domain: zwave_js
    device_id: !input button
    type: zwave_js.value_notification.Central_Scene
    property: scene
    property_key: "003"
    command_class: 91
    endpoint: 0
    value: "0"
    id: btn3_press
  - platform: device
    domain: zwave_js
    device_id: !input button
    type: zwave_js.value_notification.Central_Scene
    property: scene
    property_key: "003"
    command_class: 91
    endpoint: 0
    value: "1"
    id: btn3_release
  - platform: device
    domain: zwave_js
    device_id: !input button
    type: zwave_js.value_notification.Central_Scene
    property: scene
    property_key: "003"
    command_class: 91
    endpoint: 0
    value: "2"
    id: btn3_long
  - platform: device
    domain: zwave_js
    device_id: !input button
    type: zwave_js.value_notification.Central_Scene
    property: scene
    property_key: "003"
    command_class: 91
    endpoint: 0
    value: "3"
    id: btn3_double

  - platform: device
    domain: zwave_js
    device_id: !input button
    type: zwave_js.value_notification.Central_Scene
    property: scene
    property_key: "004"
    command_class: 91
    endpoint: 0
    value: "0"
    id: btn4_press
  - platform: device
    domain: zwave_js
    device_id: !input button
    type: zwave_js.value_notification.Central_Scene
    property: scene
    property_key: "004"
    command_class: 91
    endpoint: 0
    value: "1"
    id: btn4_release
  - platform: device
    domain: zwave_js
    device_id: !input button
    type: zwave_js.value_notification.Central_Scene
    property: scene
    property_key: "004"
    command_class: 91
    endpoint: 0
    value: "2"
    id: btn4_long
  - platform: device
    domain: zwave_js
    device_id: !input button
    type: zwave_js.value_notification.Central_Scene
    property: scene
    property_key: "004"
    command_class: 91
    endpoint: 0
    value: "3"
    id: btn4_double

action:
  - choose:
    - conditions:
        - condition: trigger
          id: btn1_press
      sequence: !input pressb1
    - conditions:
        - condition: trigger
          id: btn1_release
      sequence: !input releaseb1
    - conditions:
        - condition: trigger
          id: btn1_double
      sequence: !input doubleb1
    - conditions:
        - condition: trigger
          id: btn1_long
      sequence: !input longb1
    - conditions:
        - condition: trigger
          id: btn2_press
      sequence: !input pressb2
    - conditions:
        - condition: trigger
          id: btn2_release
      sequence: !input releaseb2
    - conditions:
        - condition: trigger
          id: btn2_double
      sequence: !input doubleb2
    - conditions:
        - condition: trigger
          id: btn2_long
      sequence: !input longb2
    - conditions:
        - condition: trigger
          id: btn3_press
      sequence: !input pressb3
    - conditions:
        - condition: trigger
          id: btn3_release
      sequence: !input releaseb3
    - conditions:
        - condition: trigger
          id: btn3_double
      sequence: !input doubleb3
    - conditions:
        - condition: trigger
          id: btn3_long
      sequence: !input longb3
    - conditions:
        - condition: trigger
          id: btn4_press
      sequence: !input pressb4
    - conditions:
        - condition: trigger
          id: btn4_release
      sequence: !input releaseb4
    - conditions:
        - condition: trigger
          id: btn4_double
      sequence: !input doubleb4
    - conditions:
        - condition: trigger
          id: btn4_long
      sequence: !input longb4
